apiVersion: v1
kind: Pod
metadata:
  name: apache-pod-dragonball
  labels:
    app: apache-dragonball
spec:
    runtimeClassName: kata-dragonball
    containers:
    - name: apache-dragonball
      image: httpd:2.4
      ports:
      - containerPort: 80
      volumeMounts:
      - name: apache-index-volume
        mountPath: /usr/local/apache2/htdocs/index.html
        subPath: index.html
    volumes:
    - name: apache-index-volume
      configMap:
        name: apache-index
---
apiVersion: v1
kind: Service
metadata:
  name: apache-dragonball-service
spec:
  type: NodePort
  selector:
    app: apache-dragonball
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30104
