apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:
    app: apache
spec:
  containers:
  - name: apache
    image: httpd:2.4
    ports:
    - containerPort: 80
    volumeMounts:
    - name: apache-index-volume
      mountPath: /usr/local/apache2/htdocs/index.html
      subPath: index.html
  volumes:
  - name: apache-index-volume
    configMap:
      name: apache-index
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30103
