apiVersion: v1
kind: Pod
metadata:
  name: caddy-pod-clh
  labels:
    app: caddy-clh
spec:
  runtimeClassName: kata-clh
  containers:
  - name: caddy-clh
    image: caddy:2.9.1
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - name: caddyfile
      mountPath: /etc/caddy/Caddyfile
      subPath: Caddyfile
  volumes:
  - name: caddyfile
    configMap:
      name: caddyfile-config
---
apiVersion: v1
kind: Service
metadata:
  name: caddy-clh-service
spec:
  type: NodePort
  selector:
    app: caddy-clh
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30110
    name: http
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30111
    name: https
