apiVersion: v1
kind: Pod
metadata:
  name: caddy-pod-dragonball
  labels:
    app: caddy-dragonball
spec:
  runtimeClassName: kata-dragonball
  containers:
  - name: caddy-dragonball
    image: caddy:2.9.1
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - name: caddyfile
      mountPath: /etc/caddy/Caddyfile
      subPath: Caddyfile
  volumes:
  - name: caddyfile
    configMap:
      name: caddyfile-config
---
apiVersion: v1
kind: Service
metadata:
  name: caddy-dragonball-service
spec:
  type: NodePort
  selector:
    app: caddy-dragonball
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30108
    name: http
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30109
    name: https
