apiVersion: v1
kind: Pod
metadata:
  name: caddy
  labels:
    app: caddy
spec:
  containers:
  - name: caddy
    image: caddy:2.9.1
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - name: caddyfile
      mountPath: /etc/caddy/Caddyfile
      subPath: Caddyfile
  volumes:
  - name: caddyfile
    configMap:
      name: caddyfile-config

---

apiVersion: v1
kind: Service
metadata:
  name: caddy-service
spec:
  type: NodePort
  selector:
    app: caddy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30106
    name: http
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30107
    name: https
