apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-dragonball
  labels:
    app: nginx-dragonball
spec:
    runtimeClassName: kata-dragonball
    containers:
    - name: nginx-dragonball
      image: docker.io/nginx:1.14.2
      ports:
      - containerPort: 80
      volumeMounts:
      - name: nginx-html
        mountPath: /usr/share/nginx/html/index.html
        subPath: index.html
    volumes:
    - name: nginx-html
      configMap:
        name: nginx-index
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dragonball-service
spec:
  type: NodePort
  selector:
    app: nginx-dragonball
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30101
